[int0]
fec = "None"
speed = "Speed10G"
autoneg = false
kr = true

[rear0]
fec = "RS"
speed = "Speed100G"

[rear1]
fec = "RS"
speed = "Speed100G"

[rear2]
fec = "RS"
speed = "Speed100G"

[rear3]
fec = "RS"
speed = "Speed100G"

[rear4]
fec = "RS"
speed = "Speed100G"

[rear5]
fec = "RS"
speed = "Speed100G"

[rear6]
fec = "RS"
speed = "Speed100G"

[rear7]
fec = "RS"
speed = "Speed100G"

[rear8]
fec = "RS"
speed = "Speed100G"

[rear9]
fec = "RS"
speed = "Speed100G"

[rear10]
fec = "RS"
speed = "Speed100G"

[rear11]
fec = "RS"
speed = "Speed100G"

[rear12]
fec = "RS"
speed = "Speed100G"

[rear13]
fec = "RS"
speed = "Speed100G"

[rear14]
fec = "RS"
speed = "Speed100G"

[rear15]
fec = "RS"
speed = "Speed100G"

[rear16]
fec = "RS"
speed = "Speed100G"

[rear17]
fec = "RS"
speed = "Speed100G"

[rear18]
fec = "RS"
speed = "Speed100G"

[rear19]
fec = "RS"
speed = "Speed100G"

[rear20]
fec = "RS"
speed = "Speed100G"

[rear21]
fec = "RS"
speed = "Speed100G"

[rear22]
fec = "RS"
speed = "Speed100G"

[rear23]
fec = "RS"
speed = "Speed100G"

[rear24]
fec = "RS"
speed = "Speed100G"

[rear25]
fec = "RS"
speed = "Speed100G"

[rear26]
fec = "RS"
speed = "Speed100G"

[rear27]
fec = "RS"
speed = "Speed100G"

[rear28]
fec = "RS"
speed = "Speed100G"

[rear29]
fec = "RS"
speed = "Speed100G"

[rear30]
fec = "RS"
speed = "Speed100G"

[rear31]
fec = "RS"
speed = "Speed100G"
