# Do not run DHCPv6 on any interfaces by default.
#
# DHCPv6 servers rely on unique identifiers, DUIDs, to identify clients.
# Those are usually based on the link-layer address. The Omicron switch zone
# starts with a random locally-administered MAC, which means we _don't_ have a
# stable ID. Dendrite software manually creates the DUID once we've collected
# stable MAC addresses from the Sidecar SP.
ifdefault StatefulAddrConf false
