[package]
name = "dpd-types-versions"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
dropshot.workspace = true
omicron-common.workspace = true
oxnet.workspace = true
rand.workspace = true
schemars.workspace = true
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true
