#!/sbin/sh

. /lib/svc/share/smf_include.sh

ROOT=/opt/oxide/dendrite

if /usr/bin/pgrep -x -u 0 uplink >/dev/null 2>&1; then
	echo "$0: uplink is already running"
	exit $SMF_EXIT_ERR_NOSMF
fi

${ROOT}/bin/uplinkd &

exit $SMF_EXIT_OK
